### ISSUE TITLE
Lkas error when reverse

### ISSUE THREAD

**Issue by Miniz199922** [sunnypilot/sunnypilot#231]
### Describe the bug

Getting lkas error when acc active and start backing up in reverse. Using wp. 2020 Jeep Grand Cherokee. Maybe when going in reverse disable acc?

### Which car does this affect?

2020 jeep

### Provide a route where the issue occurs

5c77528ab6bf019a|2023-10-22--15-47-58--0

### openpilot version

0.9.4.1

**Comment by sunnyhaibin** [comment]
This should be resolved in the latest branches. If it is still an issue, please feel free to open another issue.
