### ISSUE TITLE
LKAS Fault

### ISSUE THREAD

**Issue by tonnytsang96** [sunnypilot/sunnypilot#253]
### Describe the bug

When I turn the wheel left or right maximum. 
COMMA 3 show LKAS fault. Thank you.

Car: Toyota Corolla 2020yr

![PXL_20231210_174524661](https://github.com/sunnyhaibin/sunnypilot/assets/46121438/3fb4f9f6-3176-40ce-920e-a1d4674bb835)

### Provide a route where the issue occurs

60dcd78f23ffcb45|2023-12-16--21-09-52

### openpilot version

0.9.5.2

**Comment by altesean** [comment]
This has also affecting me on a 2020 Rav4 a few times, seems to happen when at full steering wheel lock during U-Turns with force applied to keep it at max during the turn if you hold the wheel loose just before lock it doesn't trip.

**Comment by siddchou** [comment]
I am also getting this error in 2024 cx-5 
![20240113_094253](https://github.com/sunnyhaibin/sunnypilot/assets/44501404/3648ddff-d2eb-4b0f-b1d7-f13ffb4a107d)

**Comment by sunnyhaibin** [comment]
This should be resolved in the latest branches. If it is still an issue, please feel free to open another issue.
