### ISSUE TITLE
LKAS Faults when starting the car

### ISSUE THREAD

**Issue by nharada1** [sunnypilot/sunnypilot#267]
### Describe the bug

I have a Comma 3X in my 2022 Chevy Bolt EUV Premier and I'd say maybe 40% of the time when I start the car I get LKAS Faults or other errors like "Cannot start controls". It's really flaky but I am able to engage sometimes.

I have a drive on Comma Connect if that will help debug, let me know who to grant access to it.

### Provide a route where the issue occurs

834e578d5412bd87/1705955510334/1705955772158

### openpilot version

0.9.5

**Comment by sunnyhaibin** [comment]
This should be resolved in the latest branches. If it is still an issue, please feel free to open another issue.
