### ISSUE TITLE
Cruise Control

### ISSUE THREAD

**Issue by t1ler-b** [sunnypilot/sunnypilot#310]
### Describe the bug

When using cruise control if the vehicle exceeds the set limit it will have a sharp braking instead of smooth.

### Which car does this affect?

2020 Honda Insight

### Provide a route where the issue occurs

982946c4534e1b3d/2024-03-22--12-08-57/0

### openpilot version

0.9.6.1

### Additional info

I've included a video since is required but have searched through and cannot not visually see the rough brake moments

**Comment by sunnyhaibin** [comment]
This is something related to longitudinal tuning. Closing as it is not a bug. Feel free to reach out to the sunnypilot community regarding longitudinal tuning. https://discord.gg/sunnypilot
