### ISSUE TITLE
LKAS Fault

### ISSUE THREAD

**Issue by Hjamesnellek** [sunnypilot/sunnypilot#314]
### Describe the bug

Every 71.5 minutes of vehicle run time the Comma 3 throws an “LKAS Fault: Restart the car to engage” error. Then the warning light comes on the dash and the vehicle displays both “Lane Departure Alert Malfunction” and “Headlight System Malfunction”. Rebooting the comma solves this issue for the next 71.5 minutes. 

This happens every time the car runs. Based on the “Elapsed time since start” function, it happens exactly at 01:11 and 30 seconds in, and then once rebooted it will happen again at exactly 02:23. I haven’t driven longer in a single shot yet, but I assume it would happen again.

This has been happening to me everyday since the latest update. 

### Which car does this affect?

Toyota Prius Prime 2017

### Provide a route where the issue occurs

N/a

### openpilot version

0.9.6.1-release

**Comment by sunnyhaibin** [comment]
This is an issue with the old SDSU firmware that's flashed on your SDSU. You can either reflash with the latest and updated SDSU that resolves this issue, or install sunnypilot 0.9.7.1 release that is being released very soon.
