### ISSUE TITLE
2019 Ford Edge Unrecognized

### ISSUE THREAD

**Issue by lance6x5** [sunnypilot/sunnypilot#341]
### Describe the bug

2019 Ford Edge Unrecognized . 

### Which car does this affect?

Ford Edge 2019

### Provide a route where the issue occurs

ab26946b857e7643/2024-05-30--23-52-20

### openpilot version

0.9.6.2

### Additional info

2019 Ford Edge ST  Unrecognized

**Comment by sunnyhaibin** [comment]
2019 Ford Edge is not officially supported in openpilot or sunnypilot at the moment.
