### ISSUE TITLE
Is VW TAOS 2024 Supported?

### ISSUE THREAD

**Issue by Mehdighz2024** [sunnypilot/sunnypilot#418]
### Describe the bug

Hi,
I have a VW TAOS 2024 and I see only 22-23 models are supported. There is no major differences between TAOS 2022/23 and 2024, so do you think I should wait for an update or it is safe to get the Comma/ Openpilot?

### Which car does this affect?

VW TAOS 2024

### Provide a route where the issue occurs

https://github.com/commaai/openpilot/blob/master/docs/CARS.md

### openpilot version

0.8.10

**Comment by Stupefacient** [comment]
Please go to our Discord for support on vehicles.
https://discord.gg/sunnypilot

Github to be used development not discussion. We will happily help you there
