### ISSUE TITLE
Discord link dow

### ISSUE THREAD

**Issue by ps3firebird** [sunnypilot/sunnypilot#444]
### Describe the bug

Can't join the sunnypilot discord the invite links are all down or expired. Sorry for this bug report could not find another way to inform ur team.
![Screenshot_20241103_135131_Discord](https://github.com/user-attachments/assets/6538e5e8-c9a0-45a3-a466-9bab33f08b13)

### Provide a route where the issue occurs

Online

### openpilot version

0000.9

**Comment by sunnyhaibin** [comment]
This is now fixed. Thanks :)
