### ISSUE TITLE
Hyundai Palisade 2023 on  palisade-2023-port-1

### ISSUE THREAD

**Issue by Falseclock** [sunnypilot/sunnypilot#455]
### Describe the bug

Type-R harness, Dashcam mode only. Does not show real speed.

### Which car does this affect?

HYUNDAI_PALISADE_2023

### Provide a route where the issue occurs

1c5bce9ae79fdd50/00000000--7731fc3413

### openpilot version

0.9.8

### Additional info

palisade-2023-port-2 available on 1c5bce9ae79fdd50/00000000--bae8325a65 
shows cam error

**Comment by sunnyhaibin** [comment]
Please report to the ongoing PR in `commaai/opendbc`: https://github.com/commaai/opendbc/pull/1273
